import json

def compare_json_lists_with_ignore(json1, json2, ignore_attributes):
    list1 = json.loads(json1)
    list2 = json.loads(json2)

    return compare_lists_with_ignore(list1, list2, ignore_attributes)

def compare_lists_with_ignore(list1, list2, ignore_attributes):
    if len(list1) != len(list2):
        return False

    for i in range(len(list1)):
        item1 = list1[i]
        item2 = list2[i]

        if not compare_objects_with_ignore(item1, item2, ignore_attributes):
            return False

    return True

def compare_objects_with_ignore(obj1, obj2, ignore_attributes):
    keys1 = set(obj1.keys()) - set(ignore_attributes)
    keys2 = set(obj2.keys()) - set(ignore_attributes)

    if keys1 != keys2:
        return False

    for key in keys1:
        value1 = obj1[key]
        value2 = obj2[key]

        if isinstance(value1, dict) and isinstance(value2, dict):
            if not compare_objects_with_ignore(value1, value2, ignore_attributes):
                return False
        elif isinstance(value1, list) and isinstance(value2, list):
            if not compare_lists_with_ignore(value1, value2, ignore_attributes):
                return False
        elif value1 != value2:
            return False

    return True

# Example usage
list1=[
    {
        "client_id": "6v5fbdqhv61n0pfsm38r3odp5u",
        "store_code": "GCPTEST",
        "document_id": "1093008",
        "document_type": "RO",
        "saleType": "RO",
        "status": "C98",
        "openDate": "01/04/2020",
        "closeDate": "01/11/2020",
        "openTime": "11:43 AM",
        "closeTime": "",
        "amountDue": "",
        "warrantyDue": "",
        "comments": "",
        "vehicle": {
            "vin": "JTJBM7FX3G5143769",
            "make": "LEXUS",
            "model": "GX460",
            "year": "16",
            "color": "SILVER",
            "engNo": "4.6_Liter",
            "dlrCd": "64504",
            "delDate": "01/11/2020",
            "stockNo": "LP200009",
        },
        "customer": {
            "id": "L213",
            "firstName": "VERONICA MICHELLE",
            "lastName": "HELDEN",
            "email": "DAVEANDVERONICA@GMAIL.COM",
            "addresses": [
                {
                    "addressLine": ["7312 HARTSHORNE SQUARE"],
                    "city": "ALEXANDRIA",
                    "state": "VA",
                    "zip": "22315",
                }
            ],
            "contacts": [
                {"desc": "Contact Number", "value": "7033146481"},
                {"desc": "Business Phone", "value": ""},
                {"desc": "Cell Phone", "value": "7033146481"},
                {"desc": "Home Phone", "value": "7033146481"},
            ],
            "company": "",
        },
        "employee": {
            "id": "5231",
            "firstName": "CHRISTOPHER COREY",
            "lastName": "MERRIWEATHER",
        },
        "hattagnumber": "T0009",
        "contactemail": "DAVEANDVERONICA@GMAIL.COM",
        "contactphone": "7033146481",
        "homephone": "7033146481",
        "cellphone": "7033146481",
        "busphone": "",
        "laborTotal": "",
        "partsTotal": "",
        "miscTotal": "",
        "golTotal": "",
        "salesTaxTotal": "",
        "deductibleTotal": "",
        "sublTotal": "",
        "schgTotal": "",
        "poNumber": "",
        "rate": "",
        "options": "SOLD-STK:LP200009 DLR:64504 ENG:4.6_Liter",
        "payment": "CASH",
        "promisedDate": "01/08/2020",
        "promisedTime": "11:00 PM",
        "waiter": False,
        "mileageIn": "35633",
        "mileageOut": "",
        "prodDate": "",
        "warExpDate": "",
        "license": "",
        "spc_ins": "",
        "serviceDetails": [
            {
                "lineCode": "A",
                "lineDesc": "CERTIFIED PRE-OWNED PDI",
                "causes": "",
                "lineTotalEstimate": "",
                "operations": [
                    {
                        "seqNo": "1",
                        "code": "001014",
                        "desc": "CERTIFIED PRE-OWNED PDI",
                        "techNo": "",
                        "lbrType": "IUC",
                        "actualHrs": "0.00",
                        "soldHrs": "2.00",
                        "cost": "",
                        "sale": "",
                        "lbrCostAmt": "",
                        "lbrSaleAmt": "",
                        "lbrSaleAcct": "46300",
                        "lbrSaleCtrlNo": "",
                        "saleCo": "",
                        "crCo": "240",
                        "feeId": "",
                        "discId": "",
                        "type": "LOP-OPS",
                        "parts": [
                            {
                                "seqNo": "2",
                                "partNo": "B1700",
                                "desc": "WASHER FLUID",
                                "qtyOrd": "0",
                                "qtyB": "0",
                                "cost": "3.20",
                                "sale": "4.16",
                                "list": "5.29",
                                "lbrCostAmt": "320",
                                "lbrSaleAmt": "416",
                                "lbrListAmt": "529",
                                "tSale": "0.00",
                                "total": "",
                                "saleAcct": "48100",
                                "saleCo": "240",
                                "partsNotes": "",
                            }
                        ],
                    }
                ],
                "techStory": {
                    "techComment": "108259 200 installed new sop amplifier assembly, verified sound is now working, note: car was taken apart before, placed all bolts and clip back in place, some missing clip in rear trunk covers, SOMEONE PREVIOUSLY HAD REMOVED ALL COVERS AND CLIPS, NO OTHER VISIBLE DAMAGE FOUND AT THIS TIME.",
                    "techEmpNo": "5483",
                    "techEmpName": "ALVELAR CASTRO,ALVARO",
                    "storyDate": "05/24/2023",
                    "storyTime": "02:11 PM",
                },
                "punchTimes": [
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/10/2023",
                        "startTime": "09:56 PM",
                        "finishTime": "09:57 PM",
                        "duration": "0.02",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/11/2023",
                        "startTime": "02:22 PM",
                        "finishTime": "02:23 PM",
                        "duration": "0.01",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/24/2023",
                        "startTime": "02:11 PM",
                        "finishTime": "02:12 PM",
                        "duration": "0.02",
                    },
                ],
            },
            {
                "lineCode": "B",
                "lineDesc": "VIRGINIA STATE INSPECTION",
                "causes": "",
                "lineTotalEstimate": "",
                "operations": [
                    {
                        "seqNo": "2",
                        "code": "VA",
                        "desc": "VIRGINIA STATE INSPECTION",
                        "techNo": "",
                        "lbrType": "IUC",
                        "actualHrs": "0.00",
                        "soldHrs": "0.30",
                        "cost": "",
                        "sale": "",
                        "lbrCostAmt": "",
                        "lbrSaleAmt": "",
                        "lbrSaleAcct": "46300",
                        "lbrSaleCtrlNo": "",
                        "saleCo": "",
                        "crCo": "240",
                        "feeId": "",
                        "discId": "",
                        "type": "LOP-OPS",
                        "parts": [],
                    }
                ],
                "techStory": {
                    "techComment": "108259 200 installed new sop amplifier assembly, verified sound is now working, note: car was taken apart before, placed all bolts and clip back in place, some missing clip in rear trunk covers, SOMEONE PREVIOUSLY HAD REMOVED ALL COVERS AND CLIPS, NO OTHER VISIBLE DAMAGE FOUND AT THIS TIME.",
                    "techEmpNo": "5483",
                    "techEmpName": "ALVELAR CASTRO,ALVARO",
                    "storyDate": "05/24/2023",
                    "storyTime": "02:11 PM",
                },
                "punchTimes": [
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/10/2023",
                        "startTime": "09:56 PM",
                        "finishTime": "09:57 PM",
                        "duration": "0.02",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/11/2023",
                        "startTime": "02:22 PM",
                        "finishTime": "02:23 PM",
                        "duration": "0.01",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/24/2023",
                        "startTime": "02:11 PM",
                        "finishTime": "02:12 PM",
                        "duration": "0.02",
                    },
                ],
            } 
        ],
        "roOperations": [
            {
                "seqNo": "1",
                "code": "001014",
                "desc": "CERTIFIED PRE-OWNED PDI",
                "techNo": "",
                "lbrType": "IUC",
                "actualHrs": "0.00",
                "soldHrs": "2.00",
                "cost": "",
                "sale": "",
                "lbrCostAmt": "",
                "lbrSaleAmt": "",
                "lbrSaleAcct": "46300",
                "lbrSaleCtrlNo": "",
                "saleCo": "",
                "crCo": "240",
                "feeId": "",
                "discId": "",
                "type": "LOP-OPS",
                "parts": [
                    {
                        "seqNo": "2",
                        "partNo": "B1700",
                        "desc": "WASHER FLUID",
                        "qtyOrd": "0",
                        "qtyB": "0",
                        "cost": "3.20",
                        "sale": "4.16",
                        "list": "5.29",
                        "lbrCostAmt": "320",
                        "lbrSaleAmt": "416",
                        "lbrListAmt": "529",
                        "tSale": "0.00",
                        "total": "",
                        "saleAcct": "48100",
                        "saleCo": "240",
                        "partsNotes": "",
                    }
                ],
            }
        ],
        "roParts": [
            {
                "seqNo": "2",
                "partNo": "B1700",
                "desc": "WASHER FLUID",
                "qtyOrd": "0",
                "qtyB": "0",
                "cost": "3.20",
                "sale": "4.16",
                "list": "5.29",
                "lbrCostAmt": "320",
                "lbrSaleAmt": "416",
                "lbrListAmt": "529",
                "tSale": "0.00",
                "total": "",
                "saleAcct": "48100",
                "saleCo": "240",
                "partsNotes": "",
            }
        ],
        "totalEstimate": "0",
        "create_date": "2023-06-22",
        "create_date_time": "2023-06-22 09:46:36 AM",
    },
	{
        "client_id": "6v5fbdqhv61n0pfsm38r3odp5u",
        "store_code": "GCPTEST",
        "document_id": "1093009",
        "document_type": "RO",
        "saleType": "RO",
        "status": "C98",
        "openDate": "01/04/2020",
        "closeDate": "01/11/2020",
        "openTime": "11:43 AM",
        "closeTime": "",
        "amountDue": "",
        "warrantyDue": "",
        "comments": "",
        "vehicle": {
            "vin": "JTJBM7FX3G5143769",
            "make": "LEXUS",
            "model": "GX460",
            "year": "16",
            "color": "SILVER",
            "engNo": "4.6_Liter",
            "dlrCd": "64504",
            "delDate": "01/11/2020",
            "stockNo": "LP200009",
        },
        "customer": {
            "id": "L213",
            "firstName": "VERONICA MICHELLE",
            "lastName": "HELDEN",
            "email": "DAVEANDVERONICA@GMAIL.COM",
            "addresses": [
                {
                    "addressLine": ["7312 HARTSHORNE SQUARE"],
                    "city": "ALEXANDRIA",
                    "state": "VA",
                    "zip": "22315",
                }
            ],
            "contacts": [
                {"desc": "Contact Number", "value": "7033146481"},
                {"desc": "Business Phone", "value": ""},
                {"desc": "Cell Phone", "value": "7033146481"},
                {"desc": "Home Phone", "value": "7033146481"},
            ],
            "company": "",
        },
        "employee": {
            "id": "5231",
            "firstName": "CHRISTOPHER COREY",
            "lastName": "MERRIWEATHER",
        },
        "hattagnumber": "T0009",
        "contactemail": "DAVEANDVERONICA@GMAIL.COM",
        "contactphone": "7033146481",
        "homephone": "7033146481",
        "cellphone": "7033146481",
        "busphone": "",
        "laborTotal": "",
        "partsTotal": "",
        "miscTotal": "",
        "golTotal": "",
        "salesTaxTotal": "",
        "deductibleTotal": "",
        "sublTotal": "",
        "schgTotal": "",
        "poNumber": "",
        "rate": "",
        "options": "SOLD-STK:LP200009 DLR:64504 ENG:4.6_Liter",
        "payment": "CASH",
        "promisedDate": "01/08/2020",
        "promisedTime": "11:00 PM",
        "waiter": False,
        "mileageIn": "35633",
        "mileageOut": "",
        "prodDate": "",
        "warExpDate": "",
        "license": "",
        "spc_ins": "",
        "serviceDetails": [
            {
                "lineCode": "A",
                "lineDesc": "CERTIFIED PRE-OWNED PDI",
                "causes": "",
                "lineTotalEstimate": "",
                "operations": [
                    {
                        "seqNo": "1",
                        "code": "001014",
                        "desc": "CERTIFIED PRE-OWNED PDI",
                        "techNo": "",
                        "lbrType": "IUC",
                        "actualHrs": "0.00",
                        "soldHrs": "2.00",
                        "cost": "",
                        "sale": "",
                        "lbrCostAmt": "",
                        "lbrSaleAmt": "",
                        "lbrSaleAcct": "46300",
                        "lbrSaleCtrlNo": "",
                        "saleCo": "",
                        "crCo": "240",
                        "feeId": "",
                        "discId": "",
                        "type": "LOP-OPS",
                        "parts": [
                            {
                                "seqNo": "2",
                                "partNo": "B1700",
                                "desc": "WASHER FLUID",
                                "qtyOrd": "0",
                                "qtyB": "0",
                                "cost": "3.20",
                                "sale": "4.16",
                                "list": "5.29",
                                "lbrCostAmt": "320",
                                "lbrSaleAmt": "416",
                                "lbrListAmt": "529",
                                "tSale": "0.00",
                                "total": "",
                                "saleAcct": "48100",
                                "saleCo": "240",
                                "partsNotes": "",
                            }
                        ],
                    }
                ],
                "techStory": {
                    "techComment": "108259 200 installed new sop amplifier assembly, verified sound is now working, note: car was taken apart before, placed all bolts and clip back in place, some missing clip in rear trunk covers, SOMEONE PREVIOUSLY HAD REMOVED ALL COVERS AND CLIPS, NO OTHER VISIBLE DAMAGE FOUND AT THIS TIME.",
                    "techEmpNo": "5483",
                    "techEmpName": "ALVELAR CASTRO,ALVARO",
                    "storyDate": "05/24/2023",
                    "storyTime": "02:11 PM",
                },
                "punchTimes": [
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/10/2023",
                        "startTime": "09:56 PM",
                        "finishTime": "09:57 PM",
                        "duration": "0.02",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/11/2023",
                        "startTime": "02:22 PM",
                        "finishTime": "02:23 PM",
                        "duration": "0.01",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/24/2023",
                        "startTime": "02:11 PM",
                        "finishTime": "02:12 PM",
                        "duration": "0.02",
                    },
                ],
            },
            {
                "lineCode": "B",
                "lineDesc": "VIRGINIA STATE INSPECTION",
                "causes": "",
                "lineTotalEstimate": "",
                "operations": [
                    {
                        "seqNo": "2",
                        "code": "VA",
                        "desc": "VIRGINIA STATE INSPECTION",
                        "techNo": "",
                        "lbrType": "IUC",
                        "actualHrs": "0.00",
                        "soldHrs": "0.30",
                        "cost": "",
                        "sale": "",
                        "lbrCostAmt": "",
                        "lbrSaleAmt": "",
                        "lbrSaleAcct": "46300",
                        "lbrSaleCtrlNo": "",
                        "saleCo": "",
                        "crCo": "240",
                        "feeId": "",
                        "discId": "",
                        "type": "LOP-OPS",
                        "parts": [],
                    }
                ],
                "techStory": {
                    "techComment": "108259 200 installed new sop amplifier assembly, verified sound is now working, note: car was taken apart before, placed all bolts and clip back in place, some missing clip in rear trunk covers, SOMEONE PREVIOUSLY HAD REMOVED ALL COVERS AND CLIPS, NO OTHER VISIBLE DAMAGE FOUND AT THIS TIME.",
                    "techEmpNo": "5483",
                    "techEmpName": "ALVELAR CASTRO,ALVARO",
                    "storyDate": "05/24/2023",
                    "storyTime": "02:11 PM",
                },
                "punchTimes": [
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/10/2023",
                        "startTime": "09:56 PM",
                        "finishTime": "09:57 PM",
                        "duration": "0.02",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/11/2023",
                        "startTime": "02:22 PM",
                        "finishTime": "02:23 PM",
                        "duration": "0.01",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/24/2023",
                        "startTime": "02:11 PM",
                        "finishTime": "02:12 PM",
                        "duration": "0.02",
                    },
                ],
            } 
        ],
        "roOperations": [
            {
                "seqNo": "1",
                "code": "001014",
                "desc": "CERTIFIED PRE-OWNED PDI",
                "techNo": "",
                "lbrType": "IUC",
                "actualHrs": "0.00",
                "soldHrs": "2.00",
                "cost": "",
                "sale": "",
                "lbrCostAmt": "",
                "lbrSaleAmt": "",
                "lbrSaleAcct": "46300",
                "lbrSaleCtrlNo": "",
                "saleCo": "",
                "crCo": "240",
                "feeId": "",
                "discId": "",
                "type": "LOP-OPS",
                "parts": [
                    {
                        "seqNo": "2",
                        "partNo": "B1700",
                        "desc": "WASHER FLUID",
                        "qtyOrd": "0",
                        "qtyB": "0",
                        "cost": "3.20",
                        "sale": "4.16",
                        "list": "5.29",
                        "lbrCostAmt": "320",
                        "lbrSaleAmt": "416",
                        "lbrListAmt": "529",
                        "tSale": "0.00",
                        "total": "",
                        "saleAcct": "48100",
                        "saleCo": "240",
                        "partsNotes": "",
                    }
                ],
            }
        ],
        "roParts": [
            {
                "seqNo": "2",
                "partNo": "B1700",
                "desc": "WASHER FLUID",
                "qtyOrd": "0",
                "qtyB": "0",
                "cost": "3.20",
                "sale": "4.16",
                "list": "5.29",
                "lbrCostAmt": "320",
                "lbrSaleAmt": "416",
                "lbrListAmt": "529",
                "tSale": "0.00",
                "total": "",
                "saleAcct": "48100",
                "saleCo": "240",
                "partsNotes": "",
            }
        ],
        "totalEstimate": "0",
        "create_date": "2023-06-22",
        "create_date_time": "2023-06-22 09:46:36 AM",
    }
]
list2=[
    {
        "client_id": "6v5fbdqhv61n0pfsm38r3odp5u",
        "store_code": "GCPTEST",
        "document_id": "1093008",
        "document_type": "RO",
        "saleType": "RO",
        "status": "C98",
        "openDate": "01/04/2020",
        "closeDate": "01/11/2020",
        "openTime": "11:43 AM",
        "closeTime": "",
        "amountDue": "",
        "warrantyDue": "",
        "comments": "",
        "vehicle": {
            "vin": "JTJBM7FX3G5143769",
            "make": "LEXUS",
            "model": "GX460",
            "year": "16",
            "color": "SILVER",
            "engNo": "4.6_Liter",
            "dlrCd": "64504",
            "delDate": "01/11/2020",
            "stockNo": "LP200009",
        },
        "customer": {
            "id": "L213",
            "firstName": "VERONICA MICHELLE",
            "lastName": "HELDEN",
            "email": "DAVEANDVERONICA@GMAIL.COM",
            "addresses": [
                {
                    "addressLine": ["7312 HARTSHORNE SQUARE"],
                    "city": "ALEXANDRIA",
                    "state": "VA",
                    "zip": "22315",
                }
            ],
            "contacts": [
                {"desc": "Contact Number", "value": "7033146481"},
                {"desc": "Business Phone", "value": ""},
                {"desc": "Cell Phone", "value": "7033146481"},
                {"desc": "Home Phone", "value": "7033146481"},
            ],
            "company": "",
        },
        "employee": {
            "id": "5231",
            "firstName": "CHRISTOPHER COREY",
            "lastName": "MERRIWEATHER",
        },
        "hattagnumber": "T0009",
        "contactemail": "DAVEANDVERONICA@GMAIL.COM",
        "contactphone": "7033146481",
        "homephone": "7033146481",
        "cellphone": "7033146481",
        "busphone": "",
        "laborTotal": "",
        "partsTotal": "",
        "miscTotal": "",
        "golTotal": "",
        "salesTaxTotal": "",
        "deductibleTotal": "",
        "sublTotal": "",
        "schgTotal": "",
        "poNumber": "",
        "rate": "",
        "options": "SOLD-STK:LP200009 DLR:64504 ENG:4.6_Liter",
        "payment": "CASH",
        "promisedDate": "01/08/2020",
        "promisedTime": "11:00 PM",
        "waiter": False,
        "mileageIn": "35633",
        "mileageOut": "",
        "prodDate": "",
        "warExpDate": "",
        "license": "",
        "spc_ins": "",
        "serviceDetails": [
            {
                "lineCode": "A",
                "lineDesc": "CERTIFIED PRE-OWNED PDI",
                "causes": "",
                "lineTotalEstimate": "",
                "operations": [
                    {
                        "seqNo": "1",
                        "code": "001014",
                        "desc": "CERTIFIED PRE-OWNED PDI",
                        "techNo": "",
                        "lbrType": "IUC",
                        "actualHrs": "0.00",
                        "soldHrs": "2.00",
                        "cost": "",
                        "sale": "",
                        "lbrCostAmt": "",
                        "lbrSaleAmt": "",
                        "lbrSaleAcct": "46300",
                        "lbrSaleCtrlNo": "",
                        "saleCo": "",
                        "crCo": "240",
                        "feeId": "",
                        "discId": "",
                        "type": "LOP-OPS",
                        "parts": [
                            {
                                "seqNo": "2",
                                "partNo": "B1700",
                                "desc": "WASHER FLUID",
                                "qtyOrd": "0",
                                "qtyB": "0",
                                "cost": "3.20",
                                "sale": "4.16",
                                "list": "5.29",
                                "lbrCostAmt": "320",
                                "lbrSaleAmt": "416",
                                "lbrListAmt": "529",
                                "tSale": "0.00",
                                "total": "",
                                "saleAcct": "48100",
                                "saleCo": "240",
                                "partsNotes": "",
                            }
                        ],
                    }
                ],
                "techStory": {
                    "techComment": "108259 200 installed new sop amplifier assembly, verified sound is now working, note: car was taken apart before, placed all bolts and clip back in place, some missing clip in rear trunk covers, SOMEONE PREVIOUSLY HAD REMOVED ALL COVERS AND CLIPS, NO OTHER VISIBLE DAMAGE FOUND AT THIS TIME.",
                    "techEmpNo": "5483",
                    "techEmpName": "ALVELAR CASTRO,ALVARO",
                    "storyDate": "05/24/2023",
                    "storyTime": "02:11 PM",
                },
                "punchTimes": [
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/10/2023",
                        "startTime": "09:56 PM",
                        "finishTime": "09:57 PM",
                        "duration": "0.02",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/11/2023",
                        "startTime": "02:22 PM",
                        "finishTime": "02:23 PM",
                        "duration": "0.01",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/24/2023",
                        "startTime": "02:11 PM",
                        "finishTime": "02:12 PM",
                        "duration": "0.02",
                    },
                ],
            },
            {
                "lineCode": "B",
                "lineDesc": "VIRGINIA STATE INSPECTION",
                "causes": "",
                "lineTotalEstimate": "",
                "operations": [
                    {
                        "seqNo": "2",
                        "code": "VA",
                        "desc": "VIRGINIA STATE INSPECTION",
                        "techNo": "",
                        "lbrType": "IUC",
                        "actualHrs": "0.00",
                        "soldHrs": "0.30",
                        "cost": "",
                        "sale": "",
                        "lbrCostAmt": "",
                        "lbrSaleAmt": "",
                        "lbrSaleAcct": "46300",
                        "lbrSaleCtrlNo": "",
                        "saleCo": "",
                        "crCo": "240",
                        "feeId": "",
                        "discId": "",
                        "type": "LOP-OPS",
                        "parts": [],
                    }
                ],
                "techStory": {
                    "techComment": "108259 200 installed new sop amplifier assembly, verified sound is now working, note: car was taken apart before, placed all bolts and clip back in place, some missing clip in rear trunk covers, SOMEONE PREVIOUSLY HAD REMOVED ALL COVERS AND CLIPS, NO OTHER VISIBLE DAMAGE FOUND AT THIS TIME.",
                    "techEmpNo": "5483",
                    "techEmpName": "ALVELAR CASTRO,ALVARO",
                    "storyDate": "05/24/2023",
                    "storyTime": "02:11 PM",
                },
                "punchTimes": [
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/10/2023",
                        "startTime": "09:56 PM",
                        "finishTime": "09:57 PM",
                        "duration": "0.02",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/11/2023",
                        "startTime": "02:22 PM",
                        "finishTime": "02:23 PM",
                        "duration": "0.01",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/24/2023",
                        "startTime": "02:11 PM",
                        "finishTime": "02:12 PM",
                        "duration": "0.02",
                    },
                ],
            } 
        ],
        "roOperations": [
            {
                "seqNo": "1",
                "code": "001014",
                "desc": "CERTIFIED PRE-OWNED PDI",
                "techNo": "",
                "lbrType": "IUC",
                "actualHrs": "0.00",
                "soldHrs": "2.00",
                "cost": "",
                "sale": "",
                "lbrCostAmt": "",
                "lbrSaleAmt": "",
                "lbrSaleAcct": "46300",
                "lbrSaleCtrlNo": "",
                "saleCo": "",
                "crCo": "240",
                "feeId": "",
                "discId": "",
                "type": "LOP-OPS",
                "parts": [
                    {
                        "seqNo": "2",
                        "partNo": "B1700",
                        "desc": "WASHER FLUID",
                        "qtyOrd": "0",
                        "qtyB": "0",
                        "cost": "3.20",
                        "sale": "4.16",
                        "list": "5.29",
                        "lbrCostAmt": "320",
                        "lbrSaleAmt": "416",
                        "lbrListAmt": "529",
                        "tSale": "0.00",
                        "total": "",
                        "saleAcct": "48100",
                        "saleCo": "240",
                        "partsNotes": "",
                    }
                ],
            }
        ],
        "roParts": [
            {
                "seqNo": "2",
                "partNo": "B1700",
                "desc": "WASHER FLUID",
                "qtyOrd": "0",
                "qtyB": "0",
                "cost": "3.20",
                "sale": "4.16",
                "list": "5.29",
                "lbrCostAmt": "320",
                "lbrSaleAmt": "416",
                "lbrListAmt": "529",
                "tSale": "0.00",
                "total": "",
                "saleAcct": "48100",
                "saleCo": "240",
                "partsNotes": "",
            }
        ],
        "totalEstimate": "0",
        "create_date": "2023-06-22",
        "create_date_time": "2023-06-22 09:46:36 AM",
    },
	{
        "client_id": "6v5fbdqhv61n0pfsm38r3odp5u",
        "store_code": "GCPTEST",
        "document_id": "1093009",
        "document_type": "RO",
        "saleType": "RO",
        "status": "C98",
        "openDate": "01/04/2020",
        "closeDate": "01/11/2020",
        "openTime": "11:43 AM",
        "closeTime": "",
        "amountDue": "",
        "warrantyDue": "",
        "comments": "",
        "vehicle": {
            "vin": "JTJBM7FX3G5143769",
            "make": "LEXUS",
            "model": "GX460",
            "year": "16",
            "color": "SILVER",
            "engNo": "4.6_Liter",
            "dlrCd": "64504",
            "delDate": "01/11/2020",
            "stockNo": "LP200009",
        },
        "customer": {
            "id": "L213",
            "firstName": "VERONICA MICHELLE",
            "lastName": "HELDEN",
            "email": "DAVEANDVERONICA@GMAIL.COM",
            "addresses": [
                {
                    "addressLine": ["7312 HARTSHORNE SQUARE"],
                    "city": "ALEXANDRIA",
                    "state": "VA",
                    "zip": "22315",
                }
            ],
            "contacts": [
                {"desc": "Contact Number", "value": "7033146481"},
                {"desc": "Business Phone", "value": ""},
                {"desc": "Cell Phone", "value": "7033146481"},
                {"desc": "Home Phone", "value": "7033146481"},
            ],
            "company": "",
        },
        "employee": {
            "id": "5231",
            "firstName": "CHRISTOPHER COREY",
            "lastName": "MERRIWEATHER",
        },
        "hattagnumber": "T0009",
        "contactemail": "DAVEANDVERONICA@GMAIL.COM",
        "contactphone": "7033146481",
        "homephone": "7033146481",
        "cellphone": "7033146481",
        "busphone": "",
        "laborTotal": "",
        "partsTotal": "",
        "miscTotal": "",
        "golTotal": "",
        "salesTaxTotal": "",
        "deductibleTotal": "",
        "sublTotal": "",
        "schgTotal": "",
        "poNumber": "",
        "rate": "",
        "options": "SOLD-STK:LP200009 DLR:64504 ENG:4.6_Liter",
        "payment": "CASH",
        "promisedDate": "01/08/2020",
        "promisedTime": "11:00 PM",
        "waiter": False,
        "mileageIn": "35633",
        "mileageOut": "",
        "prodDate": "",
        "warExpDate": "",
        "license": "",
        "spc_ins": "",
        "serviceDetails": [
            {
                "lineCode": "A",
                "lineDesc": "CERTIFIED PRE-OWNED PDI",
                "causes": "",
                "lineTotalEstimate": "",
                "operations": [
                    {
                        "seqNo": "1",
                        "code": "001014",
                        "desc": "CERTIFIED PRE-OWNED PDI",
                        "techNo": "",
                        "lbrType": "IUC",
                        "actualHrs": "0.00",
                        "soldHrs": "2.00",
                        "cost": "",
                        "sale": "",
                        "lbrCostAmt": "",
                        "lbrSaleAmt": "",
                        "lbrSaleAcct": "46300",
                        "lbrSaleCtrlNo": "",
                        "saleCo": "",
                        "crCo": "240",
                        "feeId": "",
                        "discId": "",
                        "type": "LOP-OPS",
                        "parts": [
                            {
                                "seqNo": "2",
                                "partNo": "B1700",
                                "desc": "WASHER FLUID",
                                "qtyOrd": "0",
                                "qtyB": "0",
                                "cost": "3.20",
                                "sale": "4.16",
                                "list": "5.29",
                                "lbrCostAmt": "320",
                                "lbrSaleAmt": "416",
                                "lbrListAmt": "529",
                                "tSale": "0.00",
                                "total": "",
                                "saleAcct": "48100",
                                "saleCo": "240",
                                "partsNotes": "",
                            }
                        ],
                    }
                ],
                "techStory": {
                    "techComment": "108259 200 installed new sop amplifier assembly, verified sound is now working, note: car was taken apart before, placed all bolts and clip back in place, some missing clip in rear trunk covers, SOMEONE PREVIOUSLY HAD REMOVED ALL COVERS AND CLIPS, NO OTHER VISIBLE DAMAGE FOUND AT THIS TIME.",
                    "techEmpNo": "5483",
                    "techEmpName": "ALVELAR CASTRO,ALVARO",
                    "storyDate": "05/24/2023",
                    "storyTime": "02:11 PM",
                },
                "punchTimes": [
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/10/2023",
                        "startTime": "09:56 PM",
                        "finishTime": "09:57 PM",
                        "duration": "0.02",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/11/2023",
                        "startTime": "02:22 PM",
                        "finishTime": "02:23 PM",
                        "duration": "0.01",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/24/2023",
                        "startTime": "02:11 PM",
                        "finishTime": "02:12 PM",
                        "duration": "0.02",
                    },
                ],
            },
            {
                "lineCode": "B",
                "lineDesc": "VIRGINIA STATE INSPECTION",
                "causes": "",
                "lineTotalEstimate": "",
                "operations": [
                    {
                        "seqNo": "2",
                        "code": "VA",
                        "desc": "VIRGINIA STATE INSPECTION",
                        "techNo": "",
                        "lbrType": "IUC",
                        "actualHrs": "0.00",
                        "soldHrs": "0.30",
                        "cost": "",
                        "sale": "",
                        "lbrCostAmt": "",
                        "lbrSaleAmt": "",
                        "lbrSaleAcct": "46300",
                        "lbrSaleCtrlNo": "",
                        "saleCo": "",
                        "crCo": "240",
                        "feeId": "",
                        "discId": "",
                        "type": "LOP-OPS",
                        "parts": [],
                    }
                ],
                "techStory": {
                    "techComment": "108259 200 installed new sop amplifier assembly, verified sound is now working, note: car was taken apart before, placed all bolts and clip back in place, some missing clip in rear trunk covers, SOMEONE PREVIOUSLY HAD REMOVED ALL COVERS AND CLIPS, NO OTHER VISIBLE DAMAGE FOUND AT THIS TIME.",
                    "techEmpNo": "5483",
                    "techEmpName": "ALVELAR CASTRO,ALVARO",
                    "storyDate": "05/24/2023",
                    "storyTime": "02:11 PM",
                },
                "punchTimes": [
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/10/2023",
                        "startTime": "09:56 PM",
                        "finishTime": "09:57 PM",
                        "duration": "0.02",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/11/2023",
                        "startTime": "02:22 PM",
                        "finishTime": "02:23 PM",
                        "duration": "0.01",
                    },
                    {
                        "techNo": "5483",
                        "type": "W",
                        "date": "05/24/2023",
                        "startTime": "02:11 PM",
                        "finishTime": "02:12 PM",
                        "duration": "0.02",
                    },
                ],
            } 
        ],
        "roOperations": [
            {
                "seqNo": "1",
                "code": "001014",
                "desc": "CERTIFIED PRE-OWNED PDI",
                "techNo": "",
                "lbrType": "IUC",
                "actualHrs": "0.00",
                "soldHrs": "2.00",
                "cost": "",
                "sale": "",
                "lbrCostAmt": "",
                "lbrSaleAmt": "",
                "lbrSaleAcct": "46300",
                "lbrSaleCtrlNo": "",
                "saleCo": "",
                "crCo": "240",
                "feeId": "",
                "discId": "",
                "type": "LOP-OPS",
                "parts": [
                    {
                        "seqNo": "2",
                        "partNo": "B1700",
                        "desc": "WASHER FLUID",
                        "qtyOrd": "0",
                        "qtyB": "0",
                        "cost": "3.20",
                        "sale": "4.16",
                        "list": "5.29",
                        "lbrCostAmt": "320",
                        "lbrSaleAmt": "416",
                        "lbrListAmt": "529",
                        "tSale": "0.00",
                        "total": "",
                        "saleAcct": "48100",
                        "saleCo": "240",
                        "partsNotes": "",
                    }
                ],
            }
        ],
        "roParts": [
            {
                "seqNo": "2",
                "partNo": "B1700",
                "desc": "WASHER FLUID",
                "qtyOrd": "0",
                "qtyB": "0",
                "cost": "3.20",
                "sale": "4.16",
                "list": "5.29",
                "lbrCostAmt": "320",
                "lbrSaleAmt": "416",
                "lbrListAmt": "529",
                "tSale": "0.00",
                "total": "",
                "saleAcct": "48100",
                "saleCo": "240",
                "partsNotes": "",
            }
        ],
        "totalEstimate": "0",
        "create_date": "2023-06-22",
        "create_date_time": "2023-06-22 09:46:36 AM",
    }
]
 
ignore_attributes = ['create_date','create_date_time']
json_string1 = json.dumps(list1)
json_string2 = json.dumps(list2)
result = compare_json_lists_with_ignore(json_string1, json_string2, ignore_attributes)
print(result)
